apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: prompt2prod
  labels:
    app: prompt2prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prompt2prod
  template:
    metadata:
      labels:
        app: prompt2prod
    spec:
      containers:
      - name: app
        image: ghcr.io/clementv78/prompt2prod:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: KGATEWAY_ENDPOINT
          value: "http://ai-gateway.kgateway-system.svc.cluster.local:8080"
        - name: OLLAMA_HOST
          value: "http://ollama:11434"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret-app
              key: Authorization
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: prompt2prod
  labels:
    app: prompt2prod
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: prompt2prod
