# Create namespace
apiVersion: v1
kind: Namespace
metadata:
  name: poc-openhands
---
# Deploy Ollama
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: poc-openhands
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
        - name: ollama
          image: ollama/ollama:latest
          ports:
            - containerPort: 11434
              name: http
          env:
            - name: OLLAMA_HOST
              value: "0.0.0.0"
          resources:
            requests:
              memory: "4Gi"
              cpu: "2"
            limits:
              memory: "8Gi"
              cpu: "4"
---
apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: poc-openhands
spec:
  ports:
    - port: 11434
      targetPort: 11434
      protocol: TCP
      name: http
  selector:
    app: ollama
---
# Deploy OpenHands
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openhands
  namespace: poc-openhands
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openhands
  template:
    metadata:
      labels:
        app: openhands
    spec:
      containers:
        - name: openhands
          image: ghcr.io/all-hands-ai/openhands:latest
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: OLLAMA_HOST
              value: "http://ollama:11434"
            - name: OPENROUTER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: llm-secrets
                  key: openrouter_api_key
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: llm-secrets
                  key: github_token
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: openhands
  namespace: poc-openhands
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: openhands
