apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: poc-openhands
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-openhands
  template:
    metadata:
      labels:
        app: poc-openhands
    spec:
      containers:
      - name: app
        image: ghcr.io/clementv78/poc-openhands:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: LLM_ENDPOINT
          value: "http://kgateway:8080/v1/chat"
        - name: OLLAMA_HOST
          value: "http://ollama:11434"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: poc-openhands
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: poc-openhands
