apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: kgateway
spec:
  gatewayClassName: kgateway
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: llm-router
spec:
  parentRefs:
    - name: kgateway
  rules:
    # Route vers Ollama pour mode local
    - matches:
        - headers:
            - name: x-llm-mode
              value: local
      backendRefs:
        - name: ollama
          port: 11434

    # Route vers OpenRouter pour mode cloud (sans URLRewrite)
    - matches:
        - headers:
            - name: x-llm-mode
              value: cloud
      backendRefs:
        - name: openrouter-proxy
          port: 443

    # Route par défaut vers Ollama
    - backendRefs:
        - name: ollama
          port: 11434
