apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ollama-deployment.yaml
  - openrouter-proxy.yaml
  - kgateway-routes.yaml
  - app-deployment.yaml
  - configmap.yaml

namespace: default
